---
- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull CloudCTL Pod Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ item.uri }}/{{ item.name }}:{{ item.tag }}'
      - 'docker-archive://{{ item.path }}/image-{{ item.name }}-{{ item.tag }}.tar'
      - --additional-tag
      - '{{ item.uri }}/{{ item.name }}:cloudctl'
    creates: "{{ dir_platform }}/images/image-{{ item.name }}-{{ item.tag }}.tar"
  with_items:
    - "{{ images_cloudctl }}"

- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull Pause Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ item.uri }}/{{ item.name }}:{{ item.tag }}'
      - 'docker-archive://{{ item.path }}/image-{{ item.name }}-{{ item.tag }}.tar'
      - --additional-tag
      - '{{ item.uri }}/{{ item.name }}:{{ item.tag }}'
    creates: "{{ dir_platform }}/images/image-{{ item.name }}-{{ item.tag }}.tar"
  with_items:
    - "{{ images_pause }}"

# RHCOS AWS VMDK
- name: '{{ ansible_name_module }} | get_url:url | Place OpenShift RHCOS Image | rhcos-aws.x86_64.vmdk.gz'
  get_url:
    url: 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.1/rhcos-aws.x86_64.vmdk.gz'
    dest: '{{ dir_platform }}/coreos/rhcos-4.6.1-aws.x86_64.vmdk.gz'
    mode: 0775
    
# Fedora CoreOS AWS VMDK
- name: '{{ ansible_name_module }} | get_url:url | Place OpenShift Fedora CoreOS Image | fedora-coreos-aws.x86_64.vmdk.xz'
  get_url:
    url: 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200629.3.0/x86_64/fedora-coreos-32.20200629.3.0-aws.x86_64.vmdk.xz'
    dest: '{{ dir_platform }}/coreos/fedora-coreos-32.20200629.3.0-aws.x86_64.vmdk.xz'
    mode: 0775    
