#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "images"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name_module }} | file:directory | Create binary path(s)' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0744'
        recurse: yes
      with_items:
        - '{{ tpdk_bin }}'

    - name: '{{ ansible_name_module }} | get_url:url | Download openshift-install binary | {{ version_openshift }}'
      unarchive:
        src: "https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-10-15-235428/openshift-install-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz"
        dest: '{{ tpdk_bin }}'
        remote_src: yes
        mode: 0775
    
    - name: '{{ ansible_name_module }} | get_url:url | Download oc binary | {{ version_openshift }}'
      unarchive:
        src: "https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-10-15-235428/openshift-client-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz"
        dest: '{{ tpdk_bin }}'
        remote_src: yes
        mode: 0775

    - name: '{{ ansible_name_module }} | get_url:url | Copy terraform binary from container | {{ version_openshift }}'
      copy:
        src: /bin/terraform
        dest: '{{ tpdk_bin }}'
        mode: 0775
